export const GESTURES = {
  SWIPE_UP: 'SWIPE_UP',
  SWIPE_DOWN: 'SWIPE_DOWN',
  SWIPE_LEFT: 'SWIPE_LEFT',
  SWIPE_RIGHT: 'SWIPE_RIGHT',
  NONE: 'NONE',
};

export const DEFAULT_SETTINGS = {
  enabled: false,
  scrollAmount: 400,
  cooldownMs: 600,
  velocityThreshold: 0.12,
  bufferSize: 8,
};

export const ACTIONS = {
  SCROLL_UP: 'SCROLL_UP',
  SCROLL_DOWN: 'SCROLL_DOWN',
  GO_BACK: 'GO_BACK',
  GO_FORWARD: 'GO_FORWARD',
  NONE: 'NONE',
};

export const DEFAULT_GESTURE_MAP = {
  [GESTURES.SWIPE_UP]: ACTIONS.SCROLL_UP,
  [GESTURES.SWIPE_DOWN]: ACTIONS.SCROLL_DOWN,
  [GESTURES.SWIPE_LEFT]: ACTIONS.GO_BACK,
  [GESTURES.SWIPE_RIGHT]: ACTIONS.GO_FORWARD,
};

export const MESSAGES = {
  GESTURE_DETECTED: 'GESTURE_DETECTED',
  TOGGLE_EXTENSION: 'TOGGLE_EXTENSION',
  GET_STATUS: 'GET_STATUS',
  STATUS_UPDATE: 'STATUS_UPDATE',
};